spring:
  application:
    name: Cloud_Api_Gateway
    
  
  cloud:
    gateway:
      routes:
      - id: welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet

    
server:
  port: 3333
  
  
